### ISSUE TITLE
Traceurs way of doing arrow functions interferes with mocha timeout

### ISSUE THREAD

**Issue by gregglind** [domenic/mocha-traceur#2]
https://github.com/google/traceur-compiler/wiki/LanguageFeatures#arrow-functions

With an arrow on the BOTH the outer and inner, this somehow breaks `this` so that `timeout` doesn't work.

Who should hear about this?  Mocha, or Traceur :)

``` javascript
// not okay, arrow on both
describe('timeout test', () => {
  it("should timeout", (done) => {
    this.timeout(500);
    setTimeout(done,300);
  });
});
```

``` javascript
// okay, arrow on outer only
describe('timeout test', () => {
  it("should timeout", function (done) {
    this.timeout(500);
    setTimeout(done,300);
  });
});
```

``` javascript
// okay, arrow on inner only
describe('timeout test', function () {
  it("should timeout", (done) => {
    this.timeout(500);
    setTimeout(done,300);
  });
});
```

Manifests as:

```
TypeError: Object #<Object> has no method 'timeout'
```

**Comment by domenic** [comment]
Arrow functions aren't methods, so they don't have a `this` binding. Just use `function` if you need `this`.

This isn't specific to Traceur, it's just part of the ES2015 language.

**Comment by gregglind** [comment]
Thanks, that clarifies it completely.

**Comment by atian25** [comment]
so any workaround with `this.timeout` ?

**Comment by domenic** [comment]
Use `function`.
